from fastapi import APIRouter, Depends, HTTPException, Query
from typing import List, Optional
from datetime import datetime, timezone
import uuid

from app.schemas.alert_schema import FraudAlertResponse, FraudCaseResponse
from app.services.alert_service import alert_dispatcher

router = APIRouter(tags=["Fraud Alerts & Cases"])


@router.get("/fraud-alerts", response_model=List[FraudAlertResponse])
async def list_fraud_alerts(
    status: Optional[str] = Query(None, description="Filter by status: OPEN, UNDER_REVIEW, RESOLVED_FRAUD"),
    severity: Optional[str] = Query(None, description="Filter by severity: LOW, MEDIUM, HIGH, CRITICAL"),
    limit: int = Query(50, ge=1, le=200)
):
    """
    Returns list of real-time fraud alerts generated by risk decision engine.
    """
    alerts: List[FraudAlertResponse] = []
    history = alert_dispatcher.history

    for tx in history:
        if tx.decision in ["BLOCK", "CHALLENGE"]:
            sev = "CRITICAL" if tx.risk_tier == "CRITICAL" else ("HIGH" if tx.decision == "BLOCK" else "MEDIUM")
            alert_status = "OPEN" if tx.decision == "BLOCK" else "UNDER_REVIEW"

            if status and alert_status.upper() != status.upper():
                continue
            if severity and sev.upper() != severity.upper():
                continue

            alerts.append(FraudAlertResponse(
                id=f"alt_{tx.transaction_id[:8]}",
                transaction_id=tx.transaction_id,
                user_id=tx.user_id,
                amount=tx.amount,
                merchant_name=tx.merchant_name,
                risk_score=tx.risk_score,
                risk_tier=tx.risk_tier,
                decision=tx.decision,
                severity=sev,
                status=alert_status,
                assigned_analyst="analyst_lead@sentinel.ai",
                created_at=tx.timestamp,
                rule_violations=tx.rule_violations,
                shap_factors=tx.shap_factors
            ))

    # Demo fallback if history is empty
    if len(alerts) == 0:
        now = datetime.now(timezone.utc)
        alerts.append(FraudAlertResponse(
            id="alt_demo_001",
            transaction_id="tx_demo_8819",
            user_id="usr_demo_101",
            amount=2450.00,
            merchant_name="Crypto Exchange X",
            risk_score=94.5,
            risk_tier="CRITICAL",
            decision="BLOCK",
            severity="CRITICAL",
            status="OPEN",
            assigned_analyst="analyst_lead@sentinel.ai",
            created_at=now,
            rule_violations=[],
            shap_factors=[]
        ))

    return alerts[:limit]


@router.get("/fraud-cases", response_model=List[FraudCaseResponse])
async def list_fraud_cases(
    status: Optional[str] = Query(None, description="Filter by case status"),
    limit: int = Query(50, ge=1, le=200)
):
    """
    Returns fraud investigation cases for fraud analyst review.
    """
    alerts = await list_fraud_alerts(status=status, limit=limit)
    cases: List[FraudCaseResponse] = []

    for idx, alt in enumerate(alerts):
        cases.append(FraudCaseResponse(
            case_id=f"case_{alt.id}",
            alert_id=alt.id,
            transaction_id=alt.transaction_id,
            customer_id=alt.user_id,
            customer_name=f"Customer {alt.user_id[:8]}",
            amount=alt.amount,
            merchant_name=alt.merchant_name,
            decision=alt.decision,
            risk_score=alt.risk_score,
            status=alt.status,
            severity=alt.severity,
            created_at=alt.created_at,
            assigned_to=alt.assigned_analyst,
            investigation_notes="Automated alert triggered by ML model (high V14/V10 SHAP contribution)."
        ))

    return cases[:limit]
