#!/usr/bin/env python3
"""
================================================================================
SentinelAI — Synthetic Customer & Transaction Ecosystem Generator
================================================================================
DISCLAIMER:
ALL DATA GENERATED BY THIS SCRIPT IS 100% SYNTHETIC, ARTIFICIALLY GENERATED
FOR SECURITY BENCHMARKING, SIMULATION, AND FRAUD DETECTION ENGINE TRAINING.
NO REAL CUSTOMER, CARDHOLDER, PII, OR FINANCIAL DATA IS ACCESSED OR STORED.
================================================================================

This module simulates a multi-entity financial ecosystem comprising:
1. Synthetic Customers (Behavioral baselines, registered devices, spending habits)
2. Synthetic Devices (Mobile iOS/Android, Desktop Windows/Mac, Linux, Unknown/Emulators)
3. Synthetic Merchants & Categories (Everyday retail to high-risk luxury & crypto)
4. Synthetic Locations & Countries (Geographic coordinates, regional IP subnets)
5. Synthetic Browsers & User Agents (Standard browsers + Tor/Automated headless bots)

Generated Transaction Scenarios:
1. Normal transactions (Baseline compliant)
2. High amount fraud (10x-50x standard spending deviation)
3. New device fraud (Unrecognized hardware/fingerprint with VPN/anomalous IP)
4. Unusual location fraud (Impossible geo-velocity / cross-border leap)
5. Rapid transaction fraud (Velocity burst / automated card-testing attack)
6. Unusual merchant fraud (Anomalous high-risk merchant category deviation)
"""

import os
import sys
import json
import uuid
import random
import argparse
from datetime import datetime, timedelta, timezone
from dataclasses import dataclass, asdict, field
from typing import List, Dict, Any, Optional, Tuple
import pandas as pd
import numpy as np

# Set deterministic seed support
DEFAULT_SEED = 42

# ==============================================================================
# 1. SYNTHETIC REFERENCE ENTITY CATALOGS
# ==============================================================================

SYNTHETIC_COUNTRIES = [
    {"country_code": "US", "country_name": "United States", "currency": "USD", "risk_weight": 0.05},
    {"country_code": "GB", "country_name": "United Kingdom", "currency": "GBP", "risk_weight": 0.06},
    {"country_code": "DE", "country_name": "Germany", "currency": "EUR", "risk_weight": 0.05},
    {"country_code": "FR", "country_name": "France", "currency": "EUR", "risk_weight": 0.05},
    {"country_code": "CA", "country_name": "Canada", "currency": "CAD", "risk_weight": 0.05},
    {"country_code": "AU", "country_name": "Australia", "currency": "AUD", "risk_weight": 0.06},
    {"country_code": "JP", "country_name": "Japan", "currency": "JPY", "risk_weight": 0.04},
    {"country_code": "SG", "country_name": "Singapore", "currency": "SGD", "risk_weight": 0.05},
    {"country_code": "BR", "country_name": "Brazil", "currency": "BRL", "risk_weight": 0.25},
    {"country_code": "NG", "country_name": "Nigeria", "currency": "NGN", "risk_weight": 0.40},
    {"country_code": "RU", "country_name": "Russian Federation", "currency": "RUB", "risk_weight": 0.45},
    {"country_code": "IN", "country_name": "India", "currency": "INR", "risk_weight": 0.12},
    {"country_code": "CY", "country_name": "Cyprus (Offshore)", "currency": "EUR", "risk_weight": 0.35},
    {"country_code": "KY", "country_name": "Cayman Islands", "currency": "USD", "risk_weight": 0.38},
]

SYNTHETIC_LOCATIONS = [
    {"city": "New York, NY", "country": "US", "lat": 40.7128, "lon": -74.0060, "ip_prefix": "198.51.100."},
    {"city": "San Francisco, CA", "country": "US", "lat": 37.7749, "lon": -122.4194, "ip_prefix": "198.51.101."},
    {"city": "Chicago, IL", "country": "US", "lat": 41.8781, "lon": -87.6298, "ip_prefix": "198.51.102."},
    {"city": "Austin, TX", "country": "US", "lat": 30.2672, "lon": -97.7431, "ip_prefix": "198.51.103."},
    {"city": "London", "country": "GB", "lat": 51.5074, "lon": -0.1278, "ip_prefix": "203.0.113."},
    {"city": "Manchester", "country": "GB", "lat": 53.4808, "lon": -2.2426, "ip_prefix": "203.0.114."},
    {"city": "Berlin", "country": "DE", "lat": 52.5200, "lon": 13.4050, "ip_prefix": "192.0.2."},
    {"city": "Munich", "country": "DE", "lat": 48.1351, "lon": 11.5820, "ip_prefix": "192.0.3."},
    {"city": "Paris", "country": "FR", "lat": 48.8566, "lon": 2.3522, "ip_prefix": "192.0.4."},
    {"city": "Toronto, ON", "country": "CA", "lat": 43.6532, "lon": -79.3832, "ip_prefix": "198.18.0."},
    {"city": "Sydney, NSW", "country": "AU", "lat": -33.8688, "lon": 151.2093, "ip_prefix": "198.19.0."},
    {"city": "Tokyo", "country": "JP", "lat": 35.6762, "lon": 139.6503, "ip_prefix": "203.0.115."},
    {"city": "Singapore", "country": "SG", "lat": 1.3521, "lon": 103.8198, "ip_prefix": "203.0.116."},
    {"city": "Mumbai", "country": "IN", "lat": 19.0760, "lon": 72.8777, "ip_prefix": "198.51.105."},
    {"city": "Sao Paulo", "country": "BR", "lat": -23.5505, "lon": -46.6333, "ip_prefix": "198.51.106."},
    {"city": "Lagos", "country": "NG", "lat": 6.5244, "lon": 3.3792, "ip_prefix": "198.51.107."},
    {"city": "Moscow", "country": "RU", "lat": 55.7558, "lon": 37.6173, "ip_prefix": "198.51.108."},
    {"city": "Limassol", "country": "CY", "lat": 34.6786, "lon": 33.0413, "ip_prefix": "198.51.109."},
    {"city": "George Town", "country": "KY", "lat": 19.2869, "lon": -81.3674, "ip_prefix": "198.51.110."},
]

SYNTHETIC_BROWSERS = [
    {"name": "Chrome 128.0 (Windows 11)", "type": "desktop", "risk_level": "low"},
    {"name": "Chrome 128.0 (macOS Sonoma)", "type": "desktop", "risk_level": "low"},
    {"name": "Safari 17.5 (iOS 17.5 iPhone)", "type": "mobile", "risk_level": "low"},
    {"name": "Safari 17.5 (macOS Sonoma)", "type": "desktop", "risk_level": "low"},
    {"name": "Edge 128.0 (Windows 11)", "type": "desktop", "risk_level": "low"},
    {"name": "Firefox 130.0 (Windows 10)", "type": "desktop", "risk_level": "low"},
    {"name": "Firefox 130.0 (Linux x86_64)", "type": "desktop", "risk_level": "low"},
    {"name": "Chrome Mobile 128.0 (Android 14)", "type": "mobile", "risk_level": "low"},
    {"name": "Samsung Internet 25.0 (Android 14)", "type": "mobile", "risk_level": "low"},
    {"name": "Opera 113.0 (Windows 11)", "type": "desktop", "risk_level": "low"},
    {"name": "Brave 1.69 (macOS)", "type": "desktop", "risk_level": "low"},
    {"name": "Tor Browser / Anonymous Onion (v13.5)", "type": "anonymous_proxy", "risk_level": "high"},
    {"name": "Headless Chrome / Puppeteer Bot (v128.0)", "type": "automated_script", "risk_level": "critical"},
    {"name": "Python-requests / Unverified Client", "type": "automated_script", "risk_level": "critical"},
]

SYNTHETIC_MERCHANTS = [
    # Standard Everyday Retail & Grocery (MCC 5411, 5311, 5814)
    {"merchant": "FreshMart Supermarket (Synthetic)", "category": "grocery", "mcc": "5411", "risk_tier": "low", "typical_min": 12.0, "typical_max": 240.0},
    {"merchant": "Target Superstore #482 (Synthetic)", "category": "retail", "mcc": "5311", "risk_tier": "low", "typical_min": 15.0, "typical_max": 350.0},
    {"merchant": "Starbucks Coffee #1042 (Synthetic)", "category": "dining", "mcc": "5814", "risk_tier": "low", "typical_min": 4.50, "typical_max": 28.0},
    {"merchant": "Chipotle Mexican Grill (Synthetic)", "category": "dining", "mcc": "5814", "risk_tier": "low", "typical_min": 11.0, "typical_max": 45.0},
    {"merchant": "Amazon Marketplace Online (Synthetic)", "category": "ecommerce", "mcc": "5999", "risk_tier": "low", "typical_min": 8.0, "typical_max": 480.0},
    {"merchant": "Shell Express Fuel (Synthetic)", "category": "fuel_dispenser", "mcc": "5541", "risk_tier": "low", "typical_min": 25.0, "typical_max": 95.0},
    {"merchant": "Uber Rides & Eats (Synthetic)", "category": "transportation", "mcc": "4121", "risk_tier": "low", "typical_min": 9.50, "typical_max": 75.0},
    {"merchant": "Netflix Subscription Service (Synthetic)", "category": "digital_goods", "mcc": "4899", "risk_tier": "low", "typical_min": 9.99, "typical_max": 24.99},
    {"merchant": "Walgreens Pharmacy (Synthetic)", "category": "pharmacy", "mcc": "5912", "risk_tier": "low", "typical_min": 8.0, "typical_max": 120.0},
    
    # Mid-Tier Electronics, Apparel & Travel (MCC 5732, 5651, 3000)
    {"merchant": "Apple Store Flagship (Synthetic)", "category": "electronics", "mcc": "5732", "risk_tier": "medium", "typical_min": 80.0, "typical_max": 2800.0},
    {"merchant": "Best Buy Supercenter (Synthetic)", "category": "electronics", "mcc": "5732", "risk_tier": "medium", "typical_min": 45.0, "typical_max": 1800.0},
    {"merchant": "Nike Town Global (Synthetic)", "category": "apparel", "mcc": "5651", "risk_tier": "medium", "typical_min": 65.0, "typical_max": 420.0},
    {"merchant": "Delta Air Lines E-Ticket (Synthetic)", "category": "airlines", "mcc": "3058", "risk_tier": "medium", "typical_min": 180.0, "typical_max": 2200.0},
    {"merchant": "Marriott Luxury Hotels (Synthetic)", "category": "lodging", "mcc": "3501", "risk_tier": "medium", "typical_min": 150.0, "typical_max": 1400.0},
    
    # High-Risk / Luxury / Crypto / Gambling (MCC 5944, 6051, 7995, 6211)
    {"merchant": "Apex Luxury Diamond Jeweler (Synthetic)", "category": "jewelry_luxury", "mcc": "5944", "risk_tier": "high", "typical_min": 1500.0, "typical_max": 15000.0},
    {"merchant": "BitQuick P2P Crypto Exchange (Synthetic)", "category": "crypto_exchange", "mcc": "6051", "risk_tier": "high", "typical_min": 500.0, "typical_max": 10000.0},
    {"merchant": "Global Swift Wire Transfer Desk (Synthetic)", "category": "money_transfer", "mcc": "4829", "risk_tier": "high", "typical_min": 800.0, "typical_max": 12500.0},
    {"merchant": "Grand Royale Online Casino (Synthetic)", "category": "gambling_casino", "mcc": "7995", "risk_tier": "high", "typical_min": 250.0, "typical_max": 8000.0},
    {"merchant": "PrivatBank Offshore Remittance (Synthetic)", "category": "offshore_banking", "mcc": "6012", "risk_tier": "high", "typical_min": 1200.0, "typical_max": 18000.0},
    {"merchant": "Anonymous Prepaid Gift Card Hub (Synthetic)", "category": "stored_value_cards", "mcc": "6540", "risk_tier": "high", "typical_min": 100.0, "typical_max": 5000.0},
]

FIRST_NAMES = ["Alexander", "Elena", "Marcus", "Sophia", "Lucas", "Amina", "Liam", "Isabella", "Chen", "Yuki", "Carlos", "Fatima", "David", "Chloe", "Viktor"]
LAST_NAMES = ["Vance", "Kowalski", "Sterling", "Dubois", "Nakamura", "Al-Mansoor", "O'Connor", "Silva", "Larsson", "Patel", "Novak", "Adeyemi", "Takahashi", "Reyes"]

# ==============================================================================
# 2. DATA CLASSES & MODELS
# ==============================================================================

@dataclass
class SyntheticDevice:
    device_id: str
    device_type: str
    model_name: str
    os_name: str
    is_trusted: bool = True
    is_synthetic: bool = True

@dataclass
class SyntheticCustomer:
    customer_id: str
    name: str
    home_country: str
    home_location: str
    home_lat: float
    home_lon: float
    home_ip_subnet: str
    registered_devices: List[str]
    preferred_browsers: List[str]
    typical_amount_mean: float
    typical_amount_std: float
    frequent_merchants: List[str]
    frequent_categories: List[str]
    account_created_at: str
    is_synthetic: bool = True

@dataclass
class SyntheticTransaction:
    transaction_id: str
    customer_id: str
    amount: float
    merchant: str
    merchant_category: str
    location: str
    country: str
    device_id: str
    ip_address: str
    browser: str
    timestamp: str
    # Audit & Benchmark Labels
    is_fraud: int
    fraud_scenario: str
    is_synthetic: bool = True
    risk_notes: str = ""

# ==============================================================================
# 3. SYNTHETIC ECOSYSTEM GENERATOR ENGINE
# ==============================================================================

class SyntheticEcosystemGenerator:
    """
    Generates a coherent synthetic population of customers, devices, and transactions
    supporting normal spending activity and 5 distinct fraud attack vectors.
    """

    def __init__(self, seed: int = DEFAULT_SEED):
        self.seed = seed
        random.seed(seed)
        np.random.seed(seed)
        self.customers: List[SyntheticCustomer] = []
        self.devices: List[SyntheticDevice] = []
        self.merchants = SYNTHETIC_MERCHANTS
        self.locations = SYNTHETIC_LOCATIONS
        self.browsers = SYNTHETIC_BROWSERS

    def generate_device_pool(self, n_devices: int = 500) -> List[SyntheticDevice]:
        """Generates a reusable catalog of hardware devices."""
        device_models = [
            ("mobile", "iPhone 15 Pro", "iOS 17.5"),
            ("mobile", "iPhone 14", "iOS 17.4"),
            ("mobile", "Samsung Galaxy S24 Ultra", "Android 14"),
            ("mobile", "Google Pixel 8 Pro", "Android 14"),
            ("desktop", "Dell XPS 15", "Windows 11"),
            ("desktop", "MacBook Pro 16 M3", "macOS Sonoma"),
            ("desktop", "Lenovo ThinkPad X1", "Windows 11"),
            ("desktop", "Custom Gaming PC", "Windows 10"),
            ("workstation", "System76 Linux Workstation", "Ubuntu 24.04"),
            ("emulator", "Nox Android Emulator (Virtual)", "Android 11"),
            ("bot_agent", "AWS EC2 Headless Linux Instance", "Alpine Linux"),
        ]

        self.devices = []
        for i in range(1, n_devices + 1):
            dtype, model, os_ver = random.choice(device_models)
            is_trust = False if dtype in ["emulator", "bot_agent"] else (random.random() > 0.05)
            dev = SyntheticDevice(
                device_id=f"SYN-DEV-{i:05d}-{uuid.uuid4().hex[:6].upper()}",
                device_type=dtype,
                model_name=model,
                os_name=os_ver,
                is_trusted=is_trust,
                is_synthetic=True
            )
            self.devices.append(dev)
        return self.devices

    def generate_customer_population(self, n_customers: int = 200) -> List[SyntheticCustomer]:
        """Generates a diverse set of synthetic cardholders with behavioral baselines."""
        if not self.devices:
            self.generate_device_pool(n_customers * 3)

        self.customers = []
        now = datetime.now(timezone.utc)

        for i in range(1, n_customers + 1):
            cust_id = f"SYN-CUST-{i:05d}"
            name = f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)} (Synthetic)"
            
            # Select home base (favor US/GB/DE/CA/AU for standard distribution)
            loc = random.choice(self.locations[:12])
            
            # Assign 1 to 3 primary devices
            cust_devices = random.sample(self.devices, k=random.randint(1, 3))
            cust_device_ids = [d.device_id for d in cust_devices]
            
            # Select standard browsers
            safe_browsers = [b["name"] for b in self.browsers if b["risk_level"] == "low"]
            cust_browsers = random.sample(safe_browsers, k=random.randint(1, 2))
            
            # Behavioral spending profile
            mean_spend = round(random.uniform(25.0, 180.0), 2)
            std_spend = round(mean_spend * random.uniform(0.25, 0.60), 2)
            
            # Frequent merchants (everyday categories)
            normal_merchants = [m["merchant"] for m in self.merchants if m["risk_tier"] in ["low", "medium"]]
            frequent_m = random.sample(normal_merchants, k=random.randint(3, 6))
            frequent_c = list(set([m["category"] for m in self.merchants if m["merchant"] in frequent_m]))
            
            created_days_ago = random.randint(60, 730)
            created_at = (now - timedelta(days=created_days_ago)).isoformat()
            
            cust = SyntheticCustomer(
                customer_id=cust_id,
                name=name,
                home_country=loc["country"],
                home_location=loc["city"],
                home_lat=loc["lat"],
                home_lon=loc["lon"],
                home_ip_subnet=loc["ip_prefix"],
                registered_devices=cust_device_ids,
                preferred_browsers=cust_browsers,
                typical_amount_mean=mean_spend,
                typical_amount_std=std_spend,
                frequent_merchants=frequent_m,
                frequent_categories=frequent_c,
                account_created_at=created_at,
                is_synthetic=True
            )
            self.customers.append(cust)
            
        return self.customers

    # --------------------------------------------------------------------------
    # 4. SCENARIO BUILDERS
    # --------------------------------------------------------------------------

    def _generate_ip(self, prefix: str) -> str:
        """Constructs an IP address within the given prefix subnet."""
        return f"{prefix}{random.randint(2, 254)}"

    def _generate_random_ip(self) -> str:
        """Constructs a random external IP address."""
        return f"{random.randint(11, 195)}.{random.randint(1, 254)}.{random.randint(1, 254)}.{random.randint(2, 254)}"

    def build_normal_transaction(self, customer: SyntheticCustomer, tx_time: datetime) -> SyntheticTransaction:
        """Scenario 1: Normal legitimate purchase aligned with customer baseline."""
        merchant_item = random.choice([m for m in self.merchants if m["merchant"] in customer.frequent_merchants or m["risk_tier"] == "low"])
        
        # Spend within Gaussian distribution of customer mean, bounded
        amount = max(3.50, round(np.random.normal(customer.typical_amount_mean, customer.typical_amount_std), 2))
        
        device_id = random.choice(customer.registered_devices)
        browser = random.choice(customer.preferred_browsers)
        ip = self._generate_ip(customer.home_ip_subnet)
        
        return SyntheticTransaction(
            transaction_id=f"SYN-TX-NORM-{uuid.uuid4().hex[:10].upper()}",
            customer_id=customer.customer_id,
            amount=amount,
            merchant=merchant_item["merchant"],
            merchant_category=merchant_item["category"],
            location=customer.home_location,
            country=customer.home_country,
            device_id=device_id,
            ip_address=ip,
            browser=browser,
            timestamp=tx_time.isoformat(),
            is_fraud=0,
            fraud_scenario="normal",
            is_synthetic=True,
            risk_notes="Legitimate transaction conforming to historical customer baselines."
        )

    def build_high_amount_fraud(self, customer: SyntheticCustomer, tx_time: datetime) -> SyntheticTransaction:
        """Scenario 2: Sudden massive monetary surge (10x-50x baseline)."""
        high_ticket_merchants = [m for m in self.merchants if m["risk_tier"] in ["medium", "high"]]
        merchant_item = random.choice(high_ticket_merchants)
        
        # Multiply baseline mean by 15x to 60x
        amount = round(customer.typical_amount_mean * random.uniform(15.0, 60.0) + random.uniform(500.0, 3000.0), 2)
        amount = min(amount, 25000.0)
        
        device_id = random.choice(customer.registered_devices)
        browser = random.choice(customer.preferred_browsers)
        ip = self._generate_ip(customer.home_ip_subnet)
        
        return SyntheticTransaction(
            transaction_id=f"SYN-TX-HIGH-{uuid.uuid4().hex[:10].upper()}",
            customer_id=customer.customer_id,
            amount=amount,
            merchant=merchant_item["merchant"],
            merchant_category=merchant_item["category"],
            location=customer.home_location,
            country=customer.home_country,
            device_id=device_id,
            ip_address=ip,
            browser=browser,
            timestamp=tx_time.isoformat(),
            is_fraud=1,
            fraud_scenario="high_amount_fraud",
            is_synthetic=True,
            risk_notes=f"Abrupt amount anomaly: ${amount:.2f} vs typical baseline ${customer.typical_amount_mean:.2f} (>15x sigma)."
        )

    def build_new_device_fraud(self, customer: SyntheticCustomer, tx_time: datetime) -> SyntheticTransaction:
        """Scenario 3: Attack initiated from an unrecognized rogue device / bot agent."""
        rogue_device_id = f"SYN-DEV-ROGUE-{uuid.uuid4().hex[:8].upper()}"
        anomalous_browser = random.choice([
            "Tor Browser / Anonymous Onion (v13.5)",
            "Headless Chrome / Puppeteer Bot (v128.0)",
            "Python-requests / Unverified Client",
            "Opera 113.0 (Windows 11)"
        ])
        
        merchant_item = random.choice([m for m in self.merchants if m["risk_tier"] in ["medium", "high"]])
        amount = round(random.uniform(350.0, 3800.0), 2)
        ip = self._generate_random_ip()
        
        return SyntheticTransaction(
            transaction_id=f"SYN-TX-NDEV-{uuid.uuid4().hex[:10].upper()}",
            customer_id=customer.customer_id,
            amount=amount,
            merchant=merchant_item["merchant"],
            merchant_category=merchant_item["category"],
            location=customer.home_location,
            country=customer.home_country,
            device_id=rogue_device_id,
            ip_address=ip,
            browser=anomalous_browser,
            timestamp=tx_time.isoformat(),
            is_fraud=1,
            fraud_scenario="new_device_fraud",
            is_synthetic=True,
            risk_notes="Unrecognized foreign device fingerprint and high-risk user agent / proxy IP."
        )

    def build_unusual_location_fraud(self, customer: SyntheticCustomer, tx_time: datetime) -> SyntheticTransaction:
        """Scenario 4: Geographical anomaly / impossible cross-border velocity."""
        # Pick location far away from customer home country
        foreign_locations = [loc for loc in self.locations if loc["country"] != customer.home_country]
        foreign_loc = random.choice(foreign_locations)
        
        merchant_item = random.choice([m for m in self.merchants if m["risk_tier"] in ["low", "medium", "high"]])
        amount = round(random.uniform(120.0, 4200.0), 2)
        
        device_id = f"SYN-DEV-GEO-{uuid.uuid4().hex[:8].upper()}"
        browser = random.choice([b["name"] for b in self.browsers])
        ip = self._generate_ip(foreign_loc["ip_prefix"])
        
        return SyntheticTransaction(
            transaction_id=f"SYN-TX-ULOC-{uuid.uuid4().hex[:10].upper()}",
            customer_id=customer.customer_id,
            amount=amount,
            merchant=merchant_item["merchant"],
            merchant_category=merchant_item["category"],
            location=foreign_loc["city"],
            country=foreign_loc["country"],
            device_id=device_id,
            ip_address=ip,
            browser=browser,
            timestamp=tx_time.isoformat(),
            is_fraud=1,
            fraud_scenario="unusual_location_fraud",
            is_synthetic=True,
            risk_notes=f"Impossible geo-velocity leap: transaction originating in {foreign_loc['city']} ({foreign_loc['country']}) vs cardholder home {customer.home_location}."
        )

    def build_rapid_transaction_fraud_burst(self, customer: SyntheticCustomer, base_time: datetime) -> List[SyntheticTransaction]:
        """Scenario 5: Rapid velocity burst (3 to 6 micro/macro transactions within 90 seconds)."""
        burst_transactions = []
        burst_count = random.randint(3, 6)
        merchants_pool = [m for m in self.merchants if m["risk_tier"] in ["low", "medium", "high"]]
        
        # Stolen card testing / automated draining
        device_id = random.choice(customer.registered_devices) if random.random() > 0.5 else f"SYN-DEV-BOT-{uuid.uuid4().hex[:6].upper()}"
        ip = self._generate_random_ip()
        browser = "Headless Chrome / Puppeteer Bot (v128.0)" if random.random() > 0.4 else random.choice(customer.preferred_browsers)
        
        current_time = base_time
        for step in range(burst_count):
            current_time += timedelta(seconds=random.randint(4, 25))
            m_item = random.choice(merchants_pool)
            amount = round(random.uniform(45.0, 950.0) if step > 0 else 1.00, 2)  # First tx often micro authorization test
            
            tx = SyntheticTransaction(
                transaction_id=f"SYN-TX-RAPID-{uuid.uuid4().hex[:10].upper()}",
                customer_id=customer.customer_id,
                amount=amount,
                merchant=m_item["merchant"],
                merchant_category=m_item["category"],
                location=customer.home_location,
                country=customer.home_country,
                device_id=device_id,
                ip_address=ip,
                browser=browser,
                timestamp=current_time.isoformat(),
                is_fraud=1,
                fraud_scenario="rapid_transaction_fraud",
                is_synthetic=True,
                risk_notes=f"Velocity burst attack: Step {step + 1}/{burst_count} executed within seconds of previous activity."
            )
            burst_transactions.append(tx)
            
        return burst_transactions

    def build_unusual_merchant_fraud(self, customer: SyntheticCustomer, tx_time: datetime) -> SyntheticTransaction:
        """Scenario 6: High-risk anomalous merchant out of character with customer profile."""
        high_risk_merchants = [m for m in self.merchants if m["risk_tier"] == "high"]
        merchant_item = random.choice(high_risk_merchants)
        
        amount = round(random.uniform(850.0, 7500.0), 2)
        device_id = random.choice(customer.registered_devices)
        browser = random.choice([b["name"] for b in self.browsers if b["risk_level"] != "critical"])
        ip = self._generate_random_ip()
        
        return SyntheticTransaction(
            transaction_id=f"SYN-TX-UMER-{uuid.uuid4().hex[:10].upper()}",
            customer_id=customer.customer_id,
            amount=amount,
            merchant=merchant_item["merchant"],
            merchant_category=merchant_item["category"],
            location=customer.home_location,
            country=customer.home_country,
            device_id=device_id,
            ip_address=ip,
            browser=browser,
            timestamp=tx_time.isoformat(),
            is_fraud=1,
            fraud_scenario="unusual_merchant_fraud",
            is_synthetic=True,
            risk_notes=f"High-risk MCC ({merchant_item['mcc']} - {merchant_item['category']}) with uncharacteristic transaction amount ${amount:.2f}."
        )

    # --------------------------------------------------------------------------
    # 5. DATASET SYNTHESIS ORCHESTRATOR
    # --------------------------------------------------------------------------

    def generate_dataset(
        self,
        n_customers: int = 250,
        n_transactions: int = 10000,
        fraud_ratio: float = 0.05,
        time_horizon_days: int = 14
    ) -> Tuple[List[SyntheticTransaction], Dict[str, Any]]:
        """
        Synthesizes the complete customer ecosystem and transactions across all 6 scenarios.
        """
        print(f"[*] Initializing Synthetic Ecosystem: {n_customers} Customers, {n_transactions} Transactions...")
        
        # 1. Initialize populations
        self.generate_customer_population(n_customers)
        
        transactions: List[SyntheticTransaction] = []
        start_time = datetime.now(timezone.utc) - timedelta(days=time_horizon_days)
        
        n_fraud_target = int(n_transactions * fraud_ratio)
        n_normal_target = n_transactions - n_fraud_target
        
        print(f"[*] Target Distribution -> Normal: {n_normal_target} | Fraudulent: {n_fraud_target} ({fraud_ratio:.2%})")
        
        scenario_counts = {
            "normal": 0,
            "high_amount_fraud": 0,
            "new_device_fraud": 0,
            "unusual_location_fraud": 0,
            "rapid_transaction_fraud": 0,
            "unusual_merchant_fraud": 0
        }
        
        # Generate Normal Baseline Transactions
        for _ in range(n_normal_target):
            cust = random.choice(self.customers)
            # Sample random timestamp in the horizon with daytime bias
            delta_seconds = random.uniform(0, time_horizon_days * 86400)
            tx_time = start_time + timedelta(seconds=delta_seconds)
            
            tx = self.build_normal_transaction(cust, tx_time)
            transactions.append(tx)
            scenario_counts["normal"] += 1

        # Generate Fraudulent Transactions across the 5 attack vectors
        fraud_scenarios = [
            "high_amount_fraud",
            "new_device_fraud",
            "unusual_location_fraud",
            "rapid_transaction_fraud",
            "unusual_merchant_fraud"
        ]
        
        while sum(v for k, v in scenario_counts.items() if k != "normal") < n_fraud_target:
            scenario = random.choice(fraud_scenarios)
            cust = random.choice(self.customers)
            delta_seconds = random.uniform(0, time_horizon_days * 86400)
            tx_time = start_time + timedelta(seconds=delta_seconds)
            
            if scenario == "high_amount_fraud":
                tx = self.build_high_amount_fraud(cust, tx_time)
                transactions.append(tx)
                scenario_counts["high_amount_fraud"] += 1
            elif scenario == "new_device_fraud":
                tx = self.build_new_device_fraud(cust, tx_time)
                transactions.append(tx)
                scenario_counts["new_device_fraud"] += 1
            elif scenario == "unusual_location_fraud":
                tx = self.build_unusual_location_fraud(cust, tx_time)
                transactions.append(tx)
                scenario_counts["unusual_location_fraud"] += 1
            elif scenario == "rapid_transaction_fraud":
                burst_txs = self.build_rapid_transaction_fraud_burst(cust, tx_time)
                for b_tx in burst_txs:
                    transactions.append(b_tx)
                    scenario_counts["rapid_transaction_fraud"] += 1
            elif scenario == "unusual_merchant_fraud":
                tx = self.build_unusual_merchant_fraud(cust, tx_time)
                transactions.append(tx)
                scenario_counts["unusual_merchant_fraud"] += 1

        # Sort chronologically
        transactions.sort(key=lambda x: x.timestamp)
        
        # Summary statistics metadata
        metadata = {
            "synthetic_generator_version": "1.0.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "total_transactions": len(transactions),
            "total_customers": len(self.customers),
            "total_devices": len(self.devices),
            "total_merchants": len(self.merchants),
            "fraud_ratio": round(sum(tx.is_fraud for tx in transactions) / len(transactions), 4),
            "scenario_breakdown": scenario_counts,
            "disclaimer": "ALL DATA IS ENTIRELY SYNTHETIC AND ARTIFICIALLY GENERATED FOR SIMULATION/BENCHMARK PURPOSES."
        }
        
        return transactions, metadata

    def export_dataset(
        self,
        transactions: List[SyntheticTransaction],
        metadata: Dict[str, Any],
        output_dir: str,
        export_csv: bool = True,
        export_json: bool = True
    ) -> Dict[str, str]:
        """Saves generated entities and transactions to disk."""
        os.makedirs(output_dir, exist_ok=True)
        saved_paths = {}

        # 1. Export Transactions
        tx_dicts = [asdict(tx) for tx in transactions]
        
        if export_csv:
            csv_path = os.path.join(output_dir, "synthetic_transactions.csv")
            df = pd.DataFrame(tx_dicts)
            df.to_csv(csv_path, index=False)
            saved_paths["transactions_csv"] = csv_path
            print(f"[+] Saved CSV: {csv_path} ({len(df)} rows)")

        if export_json:
            json_path = os.path.join(output_dir, "synthetic_transactions.json")
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump({"metadata": metadata, "transactions": tx_dicts}, f, indent=2)
            saved_paths["transactions_json"] = json_path
            print(f"[+] Saved JSON: {json_path}")

        # 2. Export Customer Profiles
        cust_path = os.path.join(output_dir, "synthetic_customers.json")
        with open(cust_path, "w", encoding="utf-8") as f:
            json.dump([asdict(c) for c in self.customers], f, indent=2)
        saved_paths["customers_json"] = cust_path

        # 3. Export Devices & Merchants Catalogs
        dev_path = os.path.join(output_dir, "synthetic_devices.json")
        with open(dev_path, "w", encoding="utf-8") as f:
            json.dump([asdict(d) for d in self.devices], f, indent=2)
        saved_paths["devices_json"] = dev_path

        merch_path = os.path.join(output_dir, "synthetic_merchants.json")
        with open(merch_path, "w", encoding="utf-8") as f:
            json.dump(self.merchants, f, indent=2)
        saved_paths["merchants_json"] = merch_path

        # 4. Export Ecosystem Metadata
        meta_path = os.path.join(output_dir, "synthetic_ecosystem_metadata.json")
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)
        saved_paths["metadata_json"] = meta_path

        return saved_paths


# ==============================================================================
# 6. CLI ENTRY POINT
# ==============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="SentinelAI — Synthetic Customer & Transaction Ecosystem Generator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--customers", type=int, default=200, help="Number of synthetic customers to generate")
    parser.add_argument("--transactions", type=int, default=10000, help="Number of synthetic transactions to generate")
    parser.add_argument("--fraud-ratio", type=float, default=0.06, help="Target proportion of fraudulent transactions")
    parser.add_argument("--days", type=int, default=14, help="Time horizon in days for timestamps")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Deterministic random seed")
    parser.add_argument("--output-dir", type=str, default=os.path.join(os.path.dirname(__file__)), help="Destination directory")
    parser.add_argument("--format", type=str, choices=["csv", "json", "both"], default="both", help="Export format")

    args = parser.parse_args()

    print("=" * 75)
    print("      SENTINEL-AI — SYNTHETIC TRANSACTION ECOSYSTEM GENERATOR")
    print("=" * 75)
    print(f" Customers Count:       {args.customers}")
    print(f" Transactions Count:    {args.transactions}")
    print(f" Fraud Ratio Target:    {args.fraud_ratio:.2%}")
    print(f" Time Horizon:          {args.days} days")
    print(f" Output Directory:      {os.path.abspath(args.output_dir)}")
    print("=" * 75)

    generator = SyntheticEcosystemGenerator(seed=args.seed)
    transactions, metadata = generator.generate_dataset(
        n_customers=args.customers,
        n_transactions=args.transactions,
        fraud_ratio=args.fraud_ratio,
        time_horizon_days=args.days
    )

    export_csv = args.format in ["csv", "both"]
    export_json = args.format in ["json", "both"]

    saved_paths = generator.export_dataset(
        transactions=transactions,
        metadata=metadata,
        output_dir=args.output_dir,
        export_csv=export_csv,
        export_json=export_json
    )

    print("\n" + "=" * 75)
    print("                     GENERATION SUMMARY")
    print("=" * 75)
    for scenario, count in metadata["scenario_breakdown"].items():
        pct = (count / metadata["total_transactions"]) * 100
        print(f"  * {scenario:<30} : {count:>6} ({pct:>5.2f}%)")
    print("-" * 75)
    print(f"  TOTAL TRANSACTIONS             : {metadata['total_transactions']:>6}")
    print(f"  TOTAL FRAUD CASES              : {sum(tx.is_fraud for tx in transactions):>6} ({metadata['fraud_ratio']:.2%})")
    print("=" * 75)
    print("[OK] Synthetic dataset generation completed successfully!\n")


if __name__ == "__main__":
    main()
